package main

// modules_test.go — what the module graph may hold (observer-maps W0.1).
//
// Two rules about go.mod that nothing else checks:
//
//   - Every module go.mod requires has its licence in THIRD_PARTY_LICENSES.md,
//     at the same version. The licences file is generated by
//     scripts/third-party-licenses.sh; a module added without re-running it
//     would ship in the binary with its licence text missing.
//   - go.mod carries no replace directive. A dependency is a tagged release
//     (FR-5.6: go-tuiMaps release candidates during BUILD, its final tag to
//     ship), never a path on one machine.

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// requireLine is one module line inside go.mod: a path and a version,
// optionally marked indirect.
var requireLine = regexp.MustCompile(`^\s*(?:require\s+)?([^\s()]+)\s+(v[^\s]+)(?:\s+//\s*indirect)?\s*$`)

// required reads the modules go.mod requires, as path → version.
func required(t *testing.T, gomod string) map[string]string {
	t.Helper()
	mods := map[string]string{}
	inBlock := false
	for _, line := range strings.Split(gomod, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "require ("):
			inBlock = true
			continue
		case inBlock && trimmed == ")":
			inBlock = false
			continue
		case !inBlock && !strings.HasPrefix(trimmed, "require "):
			continue
		}
		if m := requireLine.FindStringSubmatch(line); m != nil {
			mods[m[1]] = m[2]
		}
	}
	return mods
}

func readRepoFile(t *testing.T, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", rel))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func TestEveryRequiredModuleHasItsLicenceListed(t *testing.T) {
	mods := required(t, readRepoFile(t, "go.mod"))
	if len(mods) == 0 {
		t.Fatal("no required module was read from go.mod — the reader is broken, so a pass would prove nothing")
	}
	licences := readRepoFile(t, "THIRD_PARTY_LICENSES.md")
	for path, version := range mods {
		if !strings.Contains(licences, "\n## "+path+" "+version+"\n") {
			t.Errorf("%s %s is required by go.mod but its licence is not in THIRD_PARTY_LICENSES.md at that version: run scripts/third-party-licenses.sh", path, version)
		}
	}
}

func TestGoModHasNoReplace(t *testing.T) {
	for i, line := range strings.Split(readRepoFile(t, "go.mod"), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "replace ") || trimmed == "replace (" {
			t.Errorf("go.mod:%d: %q — a dependency is a tagged release, never a replace (FR-5.6)", i+1, trimmed)
		}
	}
}

// TestTheModuleReaderSeesBothForms holds the reader itself: a single-line
// require and a block, direct and indirect.
func TestTheModuleReaderSeesBothForms(t *testing.T) {
	got := required(t, "module x\n\nrequire a.example/one v1.2.3\n\nrequire (\n\tb.example/two v0.1.0\n\tc.example/three v0.0.0-2020 // indirect\n)\n")
	want := map[string]string{"a.example/one": "v1.2.3", "b.example/two": "v0.1.0", "c.example/three": "v0.0.0-2020"}
	if len(got) != len(want) {
		t.Fatalf("read %v, want %v", got, want)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: read %q, want %q", k, got[k], v)
		}
	}
}
