#!/bin/sh
# Regenerates THIRD_PARTY_LICENSES.md: the licence text of every module the
# binary links (Apache-2.0 and BSD-3 require the text to accompany a binary
# distribution). Reads the module cache — run after `go mod tidy`. Modules
# without a licence file are listed so the gap is visible, never silent.
set -eu
cd "$(dirname "$0")/.."
out=THIRD_PARTY_LICENSES.md
{
  echo "# Third-party licences"
  echo
  echo "Watchpost is MIT (see LICENSE). The binaries also contain the following modules, under"
  echo "their own licences, reproduced here as those licences require. Generated by"
  echo "\`scripts/third-party-licenses.sh\` from \`go list -m all\`."
  echo
  go list -m -json all | awk '
    /"Path":/   { gsub(/[",]/, "", $2); path=$2 }
    /"Version":/{ gsub(/[",]/, "", $2); ver=$2 }
    /"Dir":/    { gsub(/[",]/, "", $2); dir=$2 }
    /"Main": true/ { main=1 }
    /^}/ { if (!main && dir != "") print path " " ver " " dir; path=""; ver=""; dir=""; main=0 }
  ' | sort | while read -r path ver dir; do
    lic=""
    for f in LICENSE LICENSE.md LICENSE.txt LICENCE COPYING LICENSE-MIT; do
      [ -f "$dir/$f" ] && { lic="$dir/$f"; break; }
    done
    echo "## $path $ver"
    echo
    if [ -n "$lic" ]; then
      echo '```'
      cat "$lic"
      echo '```'
    else
      echo "_no licence file found in the module — check upstream before shipping_"
    fi
    echo
  done
} > "$out"
echo "third-party-licenses: wrote $out ($(grep -c '^## ' "$out") modules, $(grep -c 'no licence file' "$out") without a file)"
